version: "3.8"

services:
  db:
    image: postgres:15
    container_name: videoflix-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: videoflix-redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: videoflix-backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:  
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  worker:
    build: .
    container_name: videoflix-worker
    restart: always
    depends_on:
      - redis
    command: ["python", "manage.py", "rqworker", "high", "low"]
    env_file:   
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:

