version: "3.8"

services:
  db:
    image: postgres:15
    container_name: videoflix-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: videoflix-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: videoflix-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=videoflix.settings
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker-thumbnail:
    build: .
    container_name: videoflix-worker-thumbnail
    restart: unless-stopped
    depends_on:
      - redis
    command: ["python", "manage.py", "rqworker", "thumbnail"]
    volumes:
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=videoflix.settings
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"

  worker-teaser:
    build: .
    container_name: videoflix-worker-teaser
    restart: unless-stopped
    depends_on:
      - redis
    command: ["python", "manage.py", "rqworker", "teaser"]
    volumes:
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=videoflix.settings
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.3"

  worker-hls:
    build: .
    container_name: videoflix-worker-hls
    restart: unless-stopped
    depends_on:
      - redis
    command: ["python", "manage.py", "rqworker", "hls"]
    volumes:
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=videoflix.settings
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.6"

  nginx:
    image: nginx:latest
    container_name: videoflix-nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  static_volume:
  media_volume:
